apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: event-processor
  namespace: kafka-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  image: xlen911/flink-job:v1.0.0
  flinkVersion: v1_20
  serviceAccount: flink
  podTemplate:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka-cluster-kafka-brokers.kafka-dev.svc.cluster.local:9092"
            - name: COUCHBASE_HOST
              value: "couchbase-svc.kafka-dev.svc.cluster.local"
            - name: COUCHBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchbase-credentials
                  key: username
            - name: COUCHBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchbase-credentials
                  key: password
  jobManager:
    resource:
      cpu: 1
      memory: "2048m"
  taskManager:
    resource:
      cpu: 1
      memory: "2048m"
    replicas: 1
  job:
    jarURI: local:///opt/flink/