apiVersion: v1
kind: Service
metadata:
  name: couchbase-ui-external
  namespace: kafka-dev
spec:
  type: LoadBalancer
  selector:
    app: couchbase
  ports:
    - name: ui
      port: 8091
      targetPort: 8091