name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versión (ej: v1.1.0)'
        required: true
        type: string
        default: 'v1.1.0'
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set version
        id: version
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Create and push Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Verificar si el tag ya existe local o remotamente para evitar errores
          if git rev-parse "${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "⚠️ El tag ${{ env.VERSION }} ya existe localmente."
          else
            git tag ${{ env.VERSION }}
            git push origin ${{ env.VERSION }}
            echo "✅ Tag ${{ env.VERSION }} creado y publicado exitosamente."
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Producer
        uses: docker/build-push-action@v6
        with:
          context: ./producer
          push: true
          tags: |
            xlen911/kafka-producer:${{ env.VERSION }}
            xlen911/kafka-producer:dev-latest

      - name: Build and push Flink Job
        uses: docker/build-push-action@v6
        with:
          context: ./flink
          push: true
          tags: |
            xlen911/flink-job:${{ env.VERSION }}
            xlen911/flink-job:dev-latest

      - name: Update image tags in Git
        run: |
          # Actualizar Producer
          sed -i "s|image: xlen911/kafka-producer:.*|image: xlen911/kafka-producer:${{ env.VERSION }}|g" kubernetes/producer/deployment.yaml
          
          # Actualizar Flink
          sed -i "s|image: xlen911/flink-job:.*|image: xlen911/flink-job:${{ env.VERSION }}|g" kubernetes/flink/flink-deployment.yaml
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add kubernetes/producer/deployment.yaml kubernetes/flink/flink-deployment.yaml
          git commit -m "[skip ci] Update images to ${{ env.VERSION }} for dev"
          git push origin HEAD:dev